config/routes.rb
Rails.application.routes.draw do
  root to: "teams#top"
  resources :users do
    resources :teams

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballballmatching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    メンバー・チームを集めて草野球をしよう！
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料でメンバー・チーム登録
  </h2>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'></h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'></h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'></h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("", class:"logo-white"), "#" %>
  <p>© 草野球パーク</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'メンバー探す', "#", class: "category-list" %></li>
      <li><%= link_to 'チームを探す', "#", class: "brand-list" %></li>
      <li><%#= link_to 'チームを登録', new_user_team_path, class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <%# if user_signed_in? %>
      <li><%= link_to "#", "#", class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', "#", method: :delete, class: "logout" %></li>
      <%# else %>
      <li><%= link_to 'ログイン', "#", class: "login" %></li>
      <li><%= link_to '新規登録', "#", class: "sign-up" %></li>
      <%# end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'></p>
    <p class='second-fotter-text'></p>
    <p class='second-fotter-text'></p>
  </div>
  <%= image_tag "", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("", class:"second-logo"), "/" %>
</header>